### ISSUE TITLE
- リフレッシュマークが出た状態でカラムが固まる。リロードボタンにも反応しなくなる

### ISSUE THREAD

**Issue by tateisu** [tateisu/SubwayTooter#36] opened 2017-05-16 17:32 UTC
- リフレッシュマークが出た状態でカラムが固まる。リロードボタンにも反応しなくなる
-- 回線状況が良いと再現しない？

**Comment by tateisu** [comment] 2017-05-16 17:37
調査中。なかなか再現しない

**Comment by H-F-M** [comment] 2017-05-16 17:43
You have close the issue about this problem to write another issue with the same subject but now i don't understand anything cause i can't read Japanese language :p

**Comment by tateisu** [comment] 2017-05-16 17:58
Since it is already reproduced problem,
there is no need to provide further information.
Is there nothing you need to know other than whether the issue is closed or not ?

**Comment by H-F-M** [comment] 2017-05-16 18:24
no, i just need to be able to know when the problem was  corrected :) but if you write only your issue in Japanese (title and comments) ... it's hard to me to know if it's ok or not ...

**Comment by H-F-M** [comment] 2017-05-19 18:25
I found one of the many ways to reproduce the problem, i made a little video to show you. I hope that will help.

It's a French files sharing site, click on the orange button **"Télécharger"

** to get it. Valid from 2017-05-19 to 2017-05-22.
there is no way to upload it on github.

https://mon-partage.fr/f/iMeFaxnp/

**Comment by tateisu** [comment] 2017-05-20 23:42
Thank you for the detailed report!

# when app start
# ColumnViewHolder(s) were prepared for visible range [0..2], and it binded to Column.
05-21 08:13:59.622  8055  8055 D SubwayTooter: ColumnViewHolder:[0] onPageCreate 通知
05-21 08:13:59.757  8055  8055 D SubwayTooter: ColumnViewHolder:[1] onPageCreate 1 のプロフィール
05-21 08:13:59.948  8055  8055 D SubwayTooter: ColumnViewHolder:[2] onPageCreate ホーム

# when close column [1]
# ColumnViewHolder(s) were unbind and bind to updated column list.
05-21 08:14:14.340  8055  8055 D SubwayTooter: ColumnViewHolder:[0] onPageDestroy  通知
05-21 08:14:14.342  8055  8055 D SubwayTooter: ColumnViewHolder:[0] onPageCreate  通知
05-21 08:14:14.561  8055  8055 D SubwayTooter: ColumnViewHolder:[1] onPageDestroy  tateisu@mastodon.juggler.jp のプロフィール
05-21 08:14:14.561  8055  8055 D SubwayTooter: ColumnViewHolder:[1] onPageCreate ホーム
05-21 08:14:14.830  8055  8055 D SubwayTooter: ColumnViewHolder:[2] onPageDestroy ホーム
05-21 08:14:14.831  8055  8055 D SubwayTooter: ColumnViewHolder:[2] onPageCreate xxxx

'onPageDestroy' in log means "bind   Column and ColumnViewHolder".
'onPageDestroy' in log means "unbind Column and ColumnViewHolder".

Looking Column 'ホーム', it binded with ColumnViewHolder[1] , then unbinded with ColumnViewHolder[2].
This order was different from expectation.
In current implementation, column just has one reference to ColumnViewHolder.
after unbind ColumnViewHolder[2], column also lost bind with ColumnViewHolder[1].
Then any event from Column 'ホーム' to ColumnViewHolder[1] was not delivered.

It is difficult to change the order of processing related to AdapterView,
but it's easy to make Column have multiple reference to ColumnViewHolder.

**Comment by tateisu** [comment] 2017-05-21 00:13
it's fix will be included on 0.6.3.

**Comment by H-F-M** [comment] 2017-05-21 09:39
Thank you !

**Closed** 2017-05-21 10:49 UTC
Labels: bug
