### ISSUE TITLE
Misskey: Status ID conversation failed

### ISSUE THREAD

**Issue by incognico** [tateisu/SubwayTooter#86] opened 2018-11-19 20:49 UTC
When browsing a remote (local)timeline with a Misskey account and then pressing reply to a post the first time it will say Status ID conversation failed but after the second try it will just work fine.

**Comment by tateisu** [comment] 2018-11-19 23:10
I've tried following, but I can't reproduce it.
- show LTL using misskey.xyz's account , then reply from mastodon.juggler.jp's account.
- show LTL using mastodon.juggler.jp's account , then reply from misskey.xyz's account.

**Comment by incognico** [comment] 2018-11-20 07:52
account in ST: misskey (lifeisabug.com) browsing local timeline of pleroma or mastodon (ex.?@niu. moe or ?@social.tchncs.de) in ST and trying to reply to any post there makes this happen for me

**Comment by tateisu** [comment] 2018-11-20 10:47
There is a problem with the behavior of the API that allows Misskey instance to capture posts from remote instances. Probably due to net delay between servers.
I sent Issue to Misskey, so please wait for their response.

**Comment by tateisu** [comment] 2018-11-20 22:45
fixed on Misskey side.

**Closed by tateisu** 2018-11-20 22:45 UTC
