### ISSUE TITLE
Run in background fail

### ISSUE THREAD

**Issue by emilio-millepiani** [tateisu/SubwayTooter#185] opened 2022-05-17 21:16 UTC
Hi!
Subway Tooter works in the background and keeps the point up to which I have read the messages and with an interval that separates them from the new ones. When I relaunch the app from the background it is as if it were not active. It appears to have been 'turned off'. The memory settings allow background work and there is no optimization. My phone is with MicroG and has no Gooogle Map.
Thanks in advance.

**Comment by tateisu** [comment] 2022-05-18 01:11
if there is account with notification enabled, 
ST does notification checking not only push from server, but also pull from client.
About periodically pull notification check, ST uses device's Alarm or Job API to start that process.
Alarm window will be adjusted by device's battery management, or ST's app setting "notification/pull notification interval".

I think these behaviors are make sense.

What are your expected behavior, what actual behavior are not ?

**Comment by emilio-millepiani** [comment] 2022-05-20 00:07
Hi! I was not clear, fault of the English translation. Notifications work perfectly. What happens is this:
1) The app runs normally;
2) I launch Chrome and load an Internet page;
3) I go back to the app and make it active;
4) the app reloads the API, reloads all the toots and doesn't notify me of the point from which I haven't yet read the toots, but places me at the beginning of the timeline and shows me the last toot posted. It does not keep the graphic sign separating the toots already read from the new ones.
All memory settings are correct (there is no battery optimisation and the app is allowed to run in the background) and all internal options are set correctly.
My ROM is a Lineageos (Android 11) with MicroG.

Thank you for your reply and for your helpfulness,
Emilio

**Comment by tateisu** [comment] 2022-05-30 11:29
Generally speaking, on Android OS, an instance of an application may be discarded by the OS while the app is in the background. The app will try to keep the previous state by saving / restoring the state to storage.
In the case of ST, the number of columns in ST can be so large that it is difficult to save and restore the state in an instant. Therefore ST does not save the timeline "at all" in flash memory.
This is the reason you lose the scroll position.

Anyway, this issue is  duplicate of https://github.com/tateisu/SubwayTooter/issues/184

**Comment by tateisu** [comment] 2023-02-11 17:33
duplicate.

**Closed by tateisu** 2023-02-11 17:33 UTC
Labels: feature request
