### ISSUE TITLE
It sometimes happens that the column refresh does not end

### ISSUE THREAD

**Issue by H-F-M** [tateisu/SubwayTooter#24] opened 2017-05-16 08:10 UTC
It sometimes happens that the column refresh does not end, it is necessary to restart Subway Tooter to make disappear the icon of refresh (The white circle with the rotating arrow) and thus allow the update of the column again.

 I can not understand the exact circumstances in order to be able to reproduce the bug, it remains very random and it is complicated to understand why this happens.

**Comment by tateisu** [comment] 2017-05-16 17:33
duplicate of #36

**Closed by tateisu** 2017-05-16 17:33 UTC
